# Generated by Django 6.0.3 on 2026-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_hour', models.PositiveIntegerField()),
                ('course_category', models.CharField(blank=True, max_length=30)),
                ('scheme', models.CharField(blank=True, max_length=50)),
                ('nsqf', models.CharField(blank=True, max_length=20)),
                ('mode', models.CharField(choices=[('offline', 'Off Campus'), ('online', 'On Campus')], default='offline', max_length=10)),
                ('caste_category', models.CharField(choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('PWD', 'PWD'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=10)),
                ('center_name', models.CharField(choices=[('inderlok', 'Inderlok'), ('janakpuri', 'Janakpuri'), ('karkardooma', 'Karkardooma')], default='inderlok', max_length=30)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('claimable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trained', models.BooleanField(default=False)),
                ('trained_date', models.CharField(blank=True, max_length=20)),
                ('certified', models.BooleanField(default=False)),
                ('certified_date', models.CharField(blank=True, max_length=20)),
                ('placed', models.BooleanField(default=False)),
            ],
        ),
    ]
