# Generated by Django 6.0.1 on 2026-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=50)),
                ('course_hour', models.PositiveIntegerField()),
                ('scheme', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], max_length=10)),
                ('caste_category', models.CharField(max_length=10)),
                ('center_name', models.CharField(choices=[('inderlok', 'inderlok'), ('janakpuri', 'janakpuri'), ('karkardooma', 'karkardooma')], max_length=30)),
                ('trained', models.BooleanField(default=False)),
                ('certified', models.BooleanField(default=False)),
                ('placed', models.BooleanField(default=False)),
            ],
        ),
    ]
