# Generated by Django 6.0.1 on 2026-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='session',
            field=models.DateField(),
        ),
    ]
