# Generated by Django 6.0.1 on 2026-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_studentdata_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='caste_category',
            field=models.CharField(choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('PWD', 'PWD'), ('GENERAL', 'GENERAL')], max_length=10),
        ),
    ]
