# Generated by Django 5.2.8 on 2026-03-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_studentdata_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='certified',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='trained',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='certified_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='claimable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='course_category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='nsqf',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='trained_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='caste_category',
            field=models.CharField(choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('PWD', 'PWD'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='center_name',
            field=models.CharField(choices=[('inderlok', 'Inderlok'), ('janakpuri', 'Janakpuri'), ('karkardooma', 'Karkardooma')], default='inderlok', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mode',
            field=models.CharField(choices=[('offline', 'Off Campus'), ('online', 'On Campus')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='scheme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='session',
            field=models.CharField(max_length=20),
        ),
    ]
