# Generated by Django 5.2.8 on 2026-06-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default='', max_length=100)),
                ('aadhaar', models.CharField(blank=True, default='', max_length=12)),
                ('course_name', models.CharField(blank=True, default='', max_length=100)),
                ('batch_code', models.CharField(blank=True, default='', max_length=20)),
                ('center_name', models.CharField(blank=True, default='', max_length=30)),
                ('opportunity_type', models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Placement', 'Placement')], default='', max_length=20)),
                ('selection_status', models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Offered', 'Offered'), ('Placed', 'Placed'), ('Shortlisted', 'Shortlisted'), ('Not Selected', 'Not Selected'), ('On Hold', 'On Hold')], default='', max_length=20)),
                ('offer_received', models.BooleanField(blank=True, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('date_applied', models.CharField(blank=True, default='', max_length=50)),
                ('joining_date', models.CharField(blank=True, default='', max_length=50)),
                ('current_status', models.CharField(blank=True, default='', max_length=100)),
                ('placed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, help_text='Linked studentdata record (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_records', to='portal.studentdata')),
            ],
            options={
                'verbose_name': 'Placement Record',
                'verbose_name_plural': 'Placement Records',
            },
        ),
    ]
