name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.14]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - name: Run Remote Deployment Commands via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        script: |
          # Since the manual run already created this folder, just navigate to it
          cd /home/ubuntu/scsptsp
          
          # Pull down the latest updates you just pushed to GitHub
          git fetch --all
          git reset --hard origin/main
          
          # Run the local deploy script to update dependencies, migrate, and restart Nginx
          chmod +x deploy.sh
          sudo ./deploy.sh
